name: 'aroom_health_bi_engine'
version: '1.0.0'
config-version: 2

profile: 'aroom_health'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  aroom_health_bi_engine:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
    semantic:
      +materialized: view
